const logo = './tempLogo.png';
const bnbIcon = './bnb.png'
const loading = './loading.gif'
const success = './sucess.png'
const failed = './error.png'
const help = './help.png'
const close = './close.png'
const nextIcon = './next.png'
const prevIcon = './prev.png'
const lightMode = './lightMode.png'
const darkMode = './darkMode.png'
const instruction = './instruction.png'
const disclaimer = './disclaimer.png'
const navIcon1: string = './navIcon1.png'
const navIcon2: string = './navIcon2.png'
const navIcon3: string = './navIcon3.png'
const navIcon1N: string = './navIcon1N.png'
const navIcon2N: string = './navIcon2N.png'
const navIcon3N: string = './navIcon3N.png'
const arrowDown: string = './arrowDown.png'
const facebook:string= './facebook.png'
const twitter:string= './twitter.png'
const instagram:string= './instagram.png'
const telegram:string= './telegram.png'
const bnbCircle:string='./bnbCircle.png'


export default { logo, bnbIcon, loading, success, failed, help, close, nextIcon, prevIcon, lightMode, darkMode, instruction, disclaimer, navIcon1, navIcon2, navIcon3, navIcon1N, navIcon2N, navIcon3N, arrowDown ,facebook,instagram,telegram,twitter,bnbCircle}